name: arcane_user
description: "User management in arcane"
version: 1.1.0
repository: https://github.com/ArcaneArts/arcane_user
environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  serviced: ">=1.0.3 <2.0.0"
  fire_crud: ">=3.1.1 <4.0.0"
  fire_crud_flutter: ">=1.3.0 <2.0.0"
  arcane_auth: ">=1.7.0 <2.0.0"
  fast_log: ">=1.0.7 <2.0.0"
  rxdart: ">=0.27.0 <1.0.0"
  toxic: ">=1.3.2 <2.0.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter: